### ISSUE TITLE
V++ for Linux!

### ISSUE THREAD

**Issue by DeroDev** [vpp-lang/vppi#5]
**Is your feature request related to a problem? Please describe.**
When trying to install V++ 1.1.0.0-pre2 on Raspbian OS, the installer says "V++ is incopatible with your OS."

**Describe the solution you would like**
I would like V++ to be ported to Linux and be compatible, or at least so it can be fully-compatible with Mono.

**Additional context**
![image](https://user-images.githubusercontent.com/75474871/107154561-328e9b80-697c-11eb-9ba8-945b32562db1.png)

**Comment by VMGP** [comment]
I will go and check the problem. Thank you for telling me!

**Comment by VMGP** [comment]
Well it seems like no V++ version is fully compatible with Linux, due to the FS path separator char.

**Comment by VMGP** [comment]
The latest version should be more compatible with Linux.
